# Generated by Django 2.2.1 on 2019-06-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('body', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Laptop'), (2, 'Desktop')])),
                ('price', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
