# Generated by Django 2.2.1 on 2019-06-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_auto_20190601_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='manufacturer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appmain.ComputerManufacture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appmain.ComputerModel'),
            preserve_default=False,
        ),
    ]
