# Generated by Django 2.2.1 on 2019-06-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_auto_20190601_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
