# Generated by Django 2.2.1 on 2019-06-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0004_auto_20190601_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computermodel',
            options={'ordering': ['id']},
        ),
    ]
